package com.alchemist;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.alchemist.helper.TestDataReader;
import com.alchemist.jsonresponse.HoloDexLiveJsonResponse;
import com.alchemist.notification.LiveStream;
import java.util.ArrayList;
import org.junit.jupiter.api.Test;

/**
 * Unit test for HoloDexLiveJsonResponse.
 */
public class TestHoloDexLiveJsonResponse {

  @Test
  void testParse() {
    HoloDexLiveJsonResponse jsonResponse = new HoloDexLiveJsonResponse(200, rawJson);

    assertEquals(jsonResponse.getStatusCode(), 200);
    ArrayList<LiveStream> streams = jsonResponse.getStream("upcoming", false);

    assertEquals(streams.size(), 11);
    assertEquals(streams.get(0).getMemberName(), "桃鈴ねね");
    assertEquals(streams.get(1).getMemberName(), "鷹嶺ルイ");
    assertEquals(streams.get(2).getMemberName(), "博衣こより");
    assertEquals(streams.get(3).getMemberName(), "風真いろは");
    assertEquals(streams.get(4).getMemberName(), "天音かなた");
    assertEquals(streams.get(5).getMemberName(), "ときのそら");
    assertEquals(streams.get(6).getMemberName(), "戌神ころね");
    assertEquals(streams.get(7).getMemberName(), "猫又おかゆ");
    assertEquals(streams.get(8).getMemberName(), "宝鐘マリン");
    assertEquals(streams.get(9).getMemberName(), "風真いろは");
    assertEquals(streams.get(10).getMemberName(), "クレイジー・オリー");
  }

  @Test
  void testMentionedChannel() {
    // streams mentioning raden
    HoloDexLiveJsonResponse response = new HoloDexLiveJsonResponse(
        200, 
        TestDataReader
          .getReader()
          .readTestData("HoloDexMentionedChannel.json"));
    ArrayList<LiveStream> streams = response.getStream("upcoming", false);
    LiveStream stream = streams.get(0);

    assertEquals(1, streams.size());

    assertEquals("赤井はあと", stream.getMemberName());
    assertEquals("jelFWBjk4qs", stream.getVideoId());
    assertEquals("【#でんちゃま】語り合おう、もんじゃで。【ホロライブ/赤井はあと/儒烏風亭らでん #ReGLOSS】", stream.getTitle());
    assertEquals("HAACHAMA Ch 赤井はあと", stream.getChannelName());
  }

  private String rawJson = "[\n"
      + "  {\n"
      + "    \"id\": \"oihpC07HClQ\",\n"
      + "    \"title\": \"【Drawing】ホワイトデーだからイラスト描いてリスナーにプレゼントす"
      + "る!!【#緋崎ガンマ / #ホロスターズ / #お絵描き #イラスト #illustration 】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"drawing\",\n"
      + "    \"published_at\": \"2023-03-12T13:44:06.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T06:00:47.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"live\",\n"
      + "    \"start_scheduled\": \"2023-03-14T06:00:00.000Z\",\n"
      + "    \"start_actual\": \"2023-03-14T06:00:47.000Z\",\n"
      + "    \"live_viewers\": 494,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCkT1u65YS49ca_LsFwcTakw\",\n"
      + "      \"name\": \"Gamma Ch. 緋崎ガンマ - UPROAR!! -\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"naHOLOSTARS UPROAR!!\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/Vc4D2y3WqlvKHqPKk8FuBkZ-Jign84IEafB6q9j1T9vNB5aKpfp4aGCOQ-f3_6Gbfz2fvJLZ2vU=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Hizaki Gamma\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"x74TiEWb3Mk\",\n"
      + "    \"title\": \"【 歌枠 】ホワイトデーのカラオケ大会【 桃鈴ねね / ホロライブ 】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"singing\",\n"
      + "    \"published_at\": \"2023-03-14T06:34:36.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T09:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T09:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCAWSyEs_Io8MtpY3m-zqILA\",\n"
      + "      \"name\": \"Nene Ch.桃鈴ねね\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"ga5th Generation (holoFive)\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/bMBMxmB1YVDVazU-8KbB6JZqUHn4YzmFiQRWwEUHCeqm5REPW7HHQChC5xE6e36aqqnXgK4a=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Momosuzu Nene\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"ArV9pPYLn4s\",\n"
      + "    \"title\": \"【歌枠/singing】4th Fes.まであと少し‼1時間歌いまくる!【鷹嶺ルイ/ホロライブ】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"singing\",\n"
      + "    \"published_at\": \"2023-03-13T23:38:19.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T09:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T09:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCs9_O1tRPMQTHQ-N_L6FU2g\",\n"
      + "      \"name\": \"Lui ch. 鷹嶺ルイ - holoX -\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"gm6th Generation -holoX-\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/R_IzGiw1xDQp0y9zVvGkF9e8Gj8wtr2_551Ez3X6gOMIj3e6jra1I1suuK_jH9FqigBj8ywg=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Takane Lui\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"jBJaIbYENL0\",\n"
      + "    \"title\": \"【弾き語り】咳?治ってねぇよ歌枠【奏手イヅル】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"singing\",\n"
      + "    \"published_at\": \"2023-03-14T05:21:48.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCZgOv3YDEs-ZnZWDYVwJdmA\",\n"
      + "      \"name\": \"Izuru Ch. 奏手イヅル\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"maHOLOSTARS 1st Gen\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/dlq5H2SBaaAq9ilOfgGm0QvcVGEieSICsdk0Hv6oADZFn5Q0ctV1nxNAiQAJiS8u_svx5YlasQE=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Kanade Izuru\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"CFE5cdL8sq0\",\n"
      + "    \"title\": \"【 #ミリしらホロライブ 】実録：ホロライブを知らない人にメンバーの性格を予想してもらってみたらこうなった!【博衣こより/ホロライブ】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"published_at\": \"2023-03-12T09:37:38.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UC6eWCld0KwmyHFbAqK3V-Rw\",\n"
      + "      \"name\": \"Koyori ch. 博衣こより - holoX -\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"gm6th Generation -holoX-\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/WO7ItKNmy6tW_NQ82g8c1y74CZSw6GsSdynsE5s2csuEok2fHRrAaGcBV3JJO-2BxEOXXA8lvw=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Hakui Koyori\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"0Zut-qEEWT4\",\n"
      + "    \"title\": \"【珍しき歌枠】WhiteDayなのでお歌を歌う配信【アルランディス/ホロスターズ】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"singing\",\n"
      + "    \"published_at\": \"2023-03-13T16:19:48.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCKeAhJvy8zgXWbh9duVjIaQ\",\n"
      + "      \"name\": \"Aruran Ch. アルランディス\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"maHOLOSTARS 1st Gen\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/Pr1gcKc8eVnFs4vsRdb_-6tDIGQbtjrckIsHRT5dF3MB44Zu5_yskKVIUlKC455WdeoO3HjZ4cY=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Arurandeisu\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"A_Rg6LZO108\",\n"
      + "    \"title\": \"可愛くてごめん - HoneyWorks / 風真いろは(cover)\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"Music_Cover\",\n"
      + "    \"published_at\": \"2023-03-13T13:30:22.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"duration\": 221,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"songcount\": 1,\n"
      + "    \"start_scheduled\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UC_vMYWcDjmfdpH6r4TTn1MQ\",\n"
      + "      \"name\": \"Iroha ch. 風真いろは - holoX -\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"gm6th Generation -holoX-\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/YK_UCAbw_pFBHSOw_LGWI-WCJDdvMP3y9mmODQ1IFEnNVvcf-M3-q22Db5TLWuAbfboMNFTMIg=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Kazama Iroha\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"rWM7vZY6uRw\",\n"
      + "    \"title\": \"【SEKIRO】#03 VSお蝶のホワイトデー隻狼!!!初見で行くぞおおお!!!!【天音かなた/ホロライブ】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"sekiro\",\n"
      + "    \"published_at\": \"2023-03-13T14:29:46.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T10:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCZlDXzGoo7d44bwdNObFacg\",\n"
      + "      \"name\": \"Kanata Ch. 天音かなた\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"fa4th Generation (holoForce)\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/TlH8nz5O9UYo5JZ_5fo4JfXdT18N0Ck27wWrulni-c1g5bwes0tVmFiSKICzI1SW7itaTkk9GA=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Amane Kanata\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"I5YPEYRJurg\",\n"
      + "    \"title\": \"【#ひろがるホロライブ】EXPO開幕直前!試練を乗り越えてイベントへ!\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"published_at\": \"2023-03-13T08:26:44.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T11:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T11:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCWsfcksUUpoEvhia0_ut0bA\",\n"
      + "      \"name\": \"holostars ホロスターズ - VTuber Group\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"0bOfficial\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/5Jn_OHkOZhZssXXwWopUQZVwnL16EJivvxTDGqVmp4Cah3nLmVTgZMQmfF-SyuMhtFkncyT9Lw=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"HOLOSTARS Official\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"9s8MLh5e73M\",\n"
      + "    \"title\": \"【Sing/歌枠】ボーカロイド曲歌いたいの配信【#ときのそら生放送 】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"singing\",\n"
      + "    \"published_at\": \"2023-03-14T07:43:16.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T11:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T11:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCp6993wxpyDPHUpavwDFqgg\",\n"
      + "      \"name\": \"SoraCh. ときのそらチャンネル\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"0v0th Generation\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/ytc/AL5GRJUjOyRvUrRPtu1nWZFJVco-L4-1Doz21LrA0Ph8CQ=s800-c-k-c0x00ffffff-no-rj-mo\",\n"
      + "      \"english_name\": \"Tokino Sora\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"2PJl48HAWRc\",\n"
      + "    \"title\": \"【】あそぼ!!!!!!!!!!!!!!!!!!!!!【】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"published_at\": \"2023-03-14T05:19:21.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T11:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T11:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UChAnqc_AY5_I3Px5dig3X1Q\",\n"
      + "      \"name\": \"Korone Ch. 戌神ころね\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"d_GAMERS\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/ytc/AL5GRJXx7mGZOLcoPNqxVLl2ZMeJ4IaRURPYVyxpsin_HA=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Inugami Korone\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"3wFu_MptJs4\",\n"
      + "    \"title\": \"キケンナアソビ / 猫又おかゆ(cover)\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"Music_Cover\",\n"
      + "    \"published_at\": \"2023-03-12T15:17:50.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"duration\": 242,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"songcount\": 1,\n"
      + "    \"start_scheduled\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCvaTdHTWBGv3MKj3KVqJVCw\",\n"
      + "      \"name\": \"Okayu Ch. 猫又おかゆ\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"d_GAMERS\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/ytc/AL5GRJX582IyVX4aZ1uptvfh9ReDNtHy1C67I9gETEz8-g=s800-c-k-c0x00ffffff-no-rj-mo\",\n"
      + "      \"english_name\": \"Nekomata Okayu\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"KuhhaERau7g\",\n"
      + "    \"title\": \"【メン限】キミたちからチョコを搾り取るバイノーラル【ホロライブ/宝鐘マリン】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"membersonly\",\n"
      + "    \"published_at\": \"2023-03-14T07:23:06.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCCzUftO8KOVkV4wQG1vkUvg\",\n"
      + "      \"name\": \"Marine Ch. 宝鐘マリン\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"ea3rd Generation (Fantasy)\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/Z2QpYUZ4-jKoFR7Ms330gRQzjI2gZ4CB_uVP6f39YysxUe1u8icrtE07ffpRxCtpu9U65MWNDA=s800-c-k-c0x00ffffff-no-nd-rj\",\n"
      + "      \"english_name\": \"Houshou Marine\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"Q8VGwlMu5Bg\",\n"
      + "    \"title\": \"【Minecraft】内装依頼💭でっかいぺこら先輩タワーの内装工事⛏【風真いろは/ホロライブ】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"topic_id\": \"minecraft\",\n"
      + "    \"published_at\": \"2023-03-13T15:53:06.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UC_vMYWcDjmfdpH6r4TTn1MQ\",\n"
      + "      \"name\": \"Iroha ch. 風真いろは - holoX -\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"gm6th Generation -holoX-\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/YK_UCAbw_pFBHSOw_LGWI-WCJDdvMP3y9mmODQ1IFEnNVvcf-M3-q22Db5TLWuAbfboMNFTMIg=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Kazama Iroha\"\n"
      + "    }\n"
      + "  },\n"
      + "  {\n"
      + "    \"id\": \"ynRtOAPgtAE\",\n"
      + "    \"title\": \"【HALU ROLEPLAY】I'M PAYING BACK THOSE CHOCOLATES YOU G"
      + "OT ME FOR VALENTINES【Hololive ID 2nd Gen】\",\n"
      + "    \"type\": \"stream\",\n"
      + "    \"published_at\": \"2023-03-13T16:06:46.000Z\",\n"
      + "    \"available_at\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"duration\": 0,\n"
      + "    \"status\": \"upcoming\",\n"
      + "    \"start_scheduled\": \"2023-03-14T12:00:00.000Z\",\n"
      + "    \"live_viewers\": 0,\n"
      + "    \"channel\": {\n"
      + "      \"id\": \"UCYz_5n-uDuChHtLo7My1HnQ\",\n"
      + "      \"name\": \"Kureiji Ollie Ch. hololive-ID\",\n"
      + "      \"org\": \"Hololive\",\n"
      + "      \"suborg\": \"kcIndonesia 2nd Gen (holoro)\",\n"
      + "      \"type\": \"vtuber\",\n"
      + "      \"photo\": \"https://yt3.ggpht.com/okAbP3i7wWmBb4JaDuqjkFsGzMCg-05LOu5K0kKGoVwhGWsLUwun8pnXTzQ_uNBoimpiVoLp4D8=s800-c-k-c0x00ffffff-no-rj\",\n"
      + "      \"english_name\": \"Kureiji Ollie\"\n"
      + "    }\n"
      + "  }\n"
      + "]";
}
